Translate harmonic map to functional component
Jo-bot86/Harmonic-Map pull request #2
Opened 2021-03-04 20:46 UTC by hankthemason

I translated the App.tsx, ControlBar.tsx, and HarmonicMap.tsx components from class-based into functional components.

2021-03-04 21:56 UTC, Jo-bot86 commented on src/App.tsx
> -type EmptyProps = {};
Cause an warning because it's unused

2021-03-04 22:23 UTC, Jo-bot86 requested changes
super contribiution! 

the error from netlify is caused by unused variables. Could you please get rid of them and change the pull request. I've found just two but maybe there are more you can find.

2021-03-04 22:23 UTC, Jo-bot86 commented on src/types.d.ts
> +type EmptyProps = {};
it's unused

2021-03-04 22:23 UTC, Jo-bot86 commented on src/types.d.ts
> +};
I think this is also unused

2021-03-04 22:50 UTC, hankthemason commented on src/types.d.ts
> +};
okay, I think I made all the changes.

2021-03-04 22:51 UTC, hankthemason commented on src/types.d.ts
> +};
let me know if you see the changes.  they are under the commit "deleted unused variables in src/types.d.ts"

2021-03-13 19:14 UTC, pitag-ha approved these changes
@davisein, @wklv and me have just had a look at this PR and it looks great, thanks! We only have one general suggestion: to use [updaters](https://stackoverflow.com/a/43639228) in state changes; and a couple of questions about watch lists we don't understand.

2021-03-13 19:14 UTC, pitag-ha commented on src/App.tsx
> +        });
Maybe we can use an [updater](https://stackoverflow.com/a/43639228) here?

```suggestion
        setState((prevState) => {
          ...prevState,
          webMidiStatus: "error"
        });
```

2021-03-13 19:14 UTC, pitag-ha commented on src/App.tsx
> +        });
Same as above

```suggestion
        setState((prevState) => {
          ...prevState,
          webMidiStatus: "initialized"
        });
```

2021-03-13 19:14 UTC, pitag-ha commented on src/App.tsx
> +  }, [state])
Why do we need to watch `state`?

2021-03-13 19:14 UTC, pitag-ha commented on src/App.tsx
> +    });
Same as above

```suggestion
    setState((prevState) => { 
      ...prevState,
      selected_input: inputId 
    });
```

2021-03-13 19:14 UTC, pitag-ha commented on src/App.tsx
> +            pressedKeys: pressedKeys});
Maybe we can both use your spread operator and an updater?

```suggestion
          setState((prevState) => {
            ...prevState,
            pressedKeys: {...prevState.pressedKeys, [e.note.number]: e.note.name as Note} });
```

2021-03-13 19:14 UTC, pitag-ha commented on src/App.tsx
> +          const pressedKeys = Object.assign(state.pressedKeys);
```suggestion
```

2021-03-13 19:14 UTC, pitag-ha commented on src/App.tsx
>            delete pressedKeys[e.note.number];
```suggestion
```

2021-03-13 19:14 UTC, pitag-ha commented on src/App.tsx
> +            pressedKeys: pressedKeys});
We could again use an updater. This would mean to delete the two lines as marked above and here it would look something like this (up to indentation):

```suggestion
          setState((prevState) => {
              const pressedKeys = Object.assign(prevState.pressedKeys);
              delete pressedKeys[e.note.number];
              return {
                  ...prevState,
                  pressedKeys: pressedKeys}
             });
```

2021-03-13 19:14 UTC, pitag-ha commented on src/components/ControlBar.tsx
> +      setAvailableInputs(generateAvailableInputs())
Here the updater is already written :)

```suggestion
      setAvailableInputs(generateAvailableInputs)
```

2021-03-13 19:14 UTC, pitag-ha commented on src/components/ControlBar.tsx
> +      setAvailableOutputs(generateAvailableOutputs())
Same

```suggestion
      setAvailableOutputs(generateAvailableOutputs)
```

2021-03-13 19:14 UTC, pitag-ha commented on src/components/ControlBar.tsx
> +  }, [webMidiInitialized, webMidiStatus])
Why are we watching both those values? What would be the difference if we only watched `webMidiInitialized`?

2021-05-06 09:41 UTC, merged